### ISSUE TITLE
Manipulate XML string

### ISSUE THREAD

**Issue by rmzelle** [nbubna/HTML#19]
I would like to use the HTML(.js) library to edit an XML string. Is this possible? Is there something analogous to http://api.jquery.com/jQuery.parseXML/ (see also http://stackoverflow.com/questions/11258415/how-to-modify-xml-with-jquery )?

**Comment by rmzelle** [comment]
Or, if I created a DOM from a string with DOMParser (https://developer.mozilla.org/en-US/docs/Web/API/DOMParser), could I use HTML(.js) to manipulate that?

**Comment by nbubna** [comment]
I haven't tried it myself, but it seems like you ought to be able to run the resulting DOM through `HTML.ify(dom);` and then manipulate it like any other DOM.

**Comment by rmzelle** [comment]
Ah, right, that looks like it should work. I already managed with native DOM methods, so feel free to close this.
