### ISSUE TITLE
files hosted on cdnjs

### ISSUE THREAD

**Issue by maruilian11** [nbubna/HTML#24]
hi, we want to add your lib on https://cdnjs.com, but i noticed some file in `dist` didn't have min file, like
`HTML.alter.js`
`HTML.emmet.js`
`HTML.stringify.js`

is that means they don't be needed for browser?
thank you very much!
https://github.com/cdnjs/cdnjs/issues/6587

**Comment by nbubna** [comment]
They are extras, plugin versions of functionality included in the main HTML.js, but not the HTML.core.js.

Except for HTML.stringify.js, that's pretty much just used for the demo on the website. It hasn't really been developed for public consumption yet.

**Comment by maruilian11** [comment]
thank you!
